### ISSUE TITLE
Compilation Failure/Missing Function Prototypes?

### ISSUE THREAD

**Issue by ferrellsl** [evanburnsdev/graphical-nrsc5#1]
I'm cross-compiling on MSYS2 and it appears that there's a missing header or missing function prototypes because I get this at link time.  

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/local.dir/src/classes/Nrsc5Helper.cpp.obj:Nrsc5Helper.cp:(.text+0x1179): undefined reference to `nrsc5_program_type_name'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/local.dir/src/classes/Nrsc5Helper.cpp.obj:Nrsc5Helper.cp:(.text+0x11f9): undefined reference to `nrsc5_service_data_type_name'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/local.dir/src/classes/Nrsc5Helper.cpp.obj:Nrsc5Helper.cp:(.text+0x1373): undefined reference to `nrsc5_open'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/local.dir/src/classes/Nrsc5Helper.cpp.obj:Nrsc5Helper.cp:(.text+0x1455): undefined reference to `nrsc5_set_freq_correction'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/local.dir/src/classes/Nrsc5Helper.cpp.obj:Nrsc5Helper.cp:(.text+0x149b): undefined reference to `nrsc5_set_frequency'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/local.dir/src/classes/Nrsc5Helper.cpp.obj:Nrsc5Helper.cp:(.text+0x14ed): undefined reference to `nrsc5_set_gain'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/local.dir/src/classes/Nrsc5Helper.cpp.obj:Nrsc5Helper.cp:(.text+0x150e): undefined reference to `nrsc5_set_callback'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/local.dir/src/classes/Nrsc5Helper.cpp.obj:Nrsc5Helper.cp:(.text+0x152d): undefined reference to `nrsc5_start'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/local.dir/src/classes/Nrsc5Helper.cpp.obj:Nrsc5Helper.cp:(.text+0x16a1): undefined reference to `nrsc5_stop'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/local.dir/src/classes/Nrsc5Helper.cpp.obj:Nrsc5Helper.cp:(.text+0x175c): undefined reference to `nrsc5_close'

**Comment by evanburnsdev** [comment]
Hey, thanks for the report.  The GUI work I did for this is using the linux GTK libraries, which compiled fine on Debian.  I haven't touched the project in two years so there's a good chance that it doesn't work on Debian at this point as well.  I'll add a readme file to indicate it's essentially abandonware.  Feel free to fork and tailor to your needs, though.  Thanks again!
